[package]
name = "rust_and_heap"
version = "0.1.0"
authors = ["Chad Koslovsky <chad@technomancyit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
